"""update table

Revision ID: 7008869dc322
Revises: 9834847a2f73
Create Date: 2025-01-29 09:11:56.988445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7008869dc322'
down_revision = '9834847a2f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('editor', 'viewer', name='role_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('editor', 'viewer', name='role_enum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
